-- DDL generated by Postico 1.5.7
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE article (
    id SERIAL PRIMARY KEY,
    title character varying(200),
    content text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX article_pkey ON article(id int4_ops);
CREATE UNIQUE INDEX article_guid_key ON article(guid text_ops);
