-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE article (
    id SERIAL PRIMARY KEY,
    title character varying(200),
    content text,
    date_created timestamp with time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX article_pkey ON article(id int4_ops);
